intelligentoss/urls.py
from django.conf.urls import url
from django.contrib import admin
from smart_import import views

urlpatterns = [
    url(r'^$', views.index, name='homepage'),
    url(r'^admin/', admin.site.urls),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^set_password/$', views.set_password, name='set_password'),
    url(r'^view_cell/$', views.view_cell, name='view_cell'),
    url(r'^loaddata/$', views.initialization, name='init'),
    url(r'^downdata/$', views.download, name='load'),
    url(r'^upexcel/$', views.upexcel, name='upexcel'),
    url(r'^downmodeexcel/$', views.big_file_download, name='downmodeexcel'),
    url(r'^addcellunion/(.*)/$', views.addcellunion, name='add'),
]

smart_import/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from tool.scrapy import *

CITYID = {"南宁市": "11001",
          "柳州市": "11002",
          "桂林市": "11003",
          "梧州市": "11004",
          "北海市": "11005",
          "防城港市": "11006",
          "钦州市": "11007",
          "贵港市": "11008",
          "玉林市": "11009",
          "百色市": "11010",
          "贺州市": "11011",
          "河池市": "11012",
          "来宾市": "11013",
          "崇左市": "11014", }
DISTRICT_ID = {
    "兴宁区": "1100102",
    "青秀区": "1100103",
    "江南区": "1100105",
    "西乡塘区": "1100107",
    "良庆区": "1100108",
    "邕宁区": "1100109",
    "武鸣县": "1100122",
    "隆安县": "1100123",
    "马山县": "1100124",
    "上林县": "1100125",
    "宾阳县": "1100126",
    "横县": "1100127",
    "城中区": "1100202", "鱼峰区": "1100203", "柳南区": "1100204", "柳北区": "1100205", "柳江县": "1100221", "柳城县": "1100222",
    "鹿寨县": "1100223", "融安县": "1100224", "融水苗族自治县": "1100225", "三江侗族自治县": "1100226", "秀峰区": "1100302",
    "叠彩区": "1100303", "象山区": "1100304", "七星区": "1100305", "雁山区": "1100311", "阳朔县": "1100321", "临桂县": "1100322",
    "灵川县": "1100323", "全州县": "1100324", "兴安县": "1100325", "永福县": "1100326", "灌阳县": "1100327",
    "龙胜各族自治县": "1100328", "资源县": "1100329", "平乐县": "1100330", "荔浦县": "1100331", "恭城瑶族自治县": "1100332",
    "万秀区": "1100403", "蝶山区": "1100404", "长洲区": "1100405", "苍梧县": "1100421", "藤县": "1100422", "蒙山县": "1100423",
    "岑溪市": "1100481", "海城区": "1100502", "银海区": "1100503", "铁山港区": "1100512", "合浦县": "1100521", "港口区": "1100602",
    "防城区": "1100603", "上思县": "1100621", "东兴市": "1100681", "钦南区": "1100702", "钦北区": "1100703", "灵山县": "1100721",
    "浦北县": "1100722", "港北区": "1100802", "港南区": "1100803", "覃塘区": "1100804", "平南县": "1100821", "桂平市": "1100881",
    "玉州区": "1100902", "容县": "1100921", "陆川县": "1100922", "博白县": "1100923", "兴业县": "1100924", "北流市": "1100981",
    "右江区": "1101002", "田阳县": "1101021", "田东县": "1101022", "平果县": "1101023", "德保县": "1101024", "靖西县": "1101025",
    "那坡县": "1101026", "凌云县": "1101027", "乐业县": "1101028", "田林县": "1101029", "西林县": "1101030",
    "隆林各族自治县": "1101031", "八步区": "1101102", "昭平县": "1101121", "钟山县": "1101122", "富川瑶族自治县": "1101123",
    "平桂区": "1101124", "金城江区": "1101202", "南丹县": "1101221", "天峨县": "1101222", "凤山县": "1101223", "东兰县": "1101224",
    "罗城仫佬族自治县": "1101225", "环江毛南族自治县": "1101226", "巴马瑶族自治县": "1101227", "都安瑶族自治县": "1101228",
    "大化瑶族自治县": "1101229", "宜州市": "1101281", "兴宾区": "1101302", "忻城县": "1101321", "象州县": "1101322",
    "武宣县": "1101323", "金秀瑶族自治县": "1101324", "合山市": "1101381", "江洲区": "1101402", "扶绥县": "1101421",
    "宁明县": "1101422", "龙州县": "1101423", "大新县": "1101424", "天等县": "1101425", "凭祥市": "1101481"}
ADMIN_REGIONSlist = {"城区": "1",
                     "县城": "2",
                     "乡镇": "3",
                     "其他": "9",
                     }
IS_Mrlist = {"未采集": "0",
             "已采集": "1",
             }
DUP_MODElist = {"FDD": "0",
                "TDD": "1",
                }
RRUCELL_FLAGlist = {"不是射频拉远的小区": "0",
                    "射频拉远的小区": "1",
                    }
COVER_TYPElist = {"室外": "1",
                  "室内": "2",
                  "室内拖室外": "3",
                  "室外拖室内": "4",
                  }
Ifnotlist = {"是": "1",
             "否": "0",
             }
CELL_ACTIVE_STATElist = {"激活": "1",
                         "去激活": "2",
                         }
HIGH_SPEED_FLAGlist = {"高速小区": "1",
                       "低速小区": "2",
                       }
TX_RX_MODElist = {
    "1T1R(一发一收)": "1",
    "1T2R(一发二收)": "2",
    "2T2R(两发两收)": "3",
    "2T4R(两发四收)": "4",
    "4T4R(四发四收)": "5",
    "8T8R(八发八收)": "6",
}

CSFBlist = {"GSM": "1",
            "WCDMA": "2",
            }
COMPANYlist = {"电信": "1",
               "联通": "2",
               }
SHARED_TYPElsit = {"独立载频": "1",
                   "共享载频": "2",
                   }
VENDOR_Idlsit = {"华为": "1",
                 "中兴": "2",
                 "诺基亚": "5",
                 }
RRU_MODELlist = {"RRU": "1",
                 "载频板": "2",
                 }


class MyUser(models.Model):
    user = models.OneToOneField(User)
    nickname = models.CharField(max_length=16)
    region = models.CharField(max_length=36)
    department = models.CharField(max_length=36)
    permission = models.IntegerField(default=1)


class BasisOss(models.Model):
    add_data_information = None
    basic_information = None
    modify_url = 'http://10.245.0.91:10101/wonop/wonop/config/maintain/detail/config_maintain_property_add_nocheckEx.action'
    def makeToOss(self):
        try:
            AbstractAsk.get_new_cookie()

            respond_msg = oss_ask(self.modify_url, self.add_data_information, None, AskModify)
            if respond_msg == 'true':
                # self.save()
                pass
        except:
            raise ValueError('input error!')

    def delete_data_oss(self):
        pass


class Antenna(BasisOss):
    antennaid = models.CharField(max_length=512)
    antennaid1 = models.CharField(max_length=512)
    province = models.CharField(max_length=512)
    city = models.CharField(max_length=512)
    district = models.CharField(max_length=512)
    lon = models.FloatField(blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)
    physicalstationid = models.CharField(max_length=512)
    rruid = models.CharField(max_length=512)
    cellid1 = models.CharField(max_length=512)
    directionangle = models.FloatField(blank=True, null=True)
    antennaheight = models.FloatField(blank=True, null=True)
    electricaldowntilt = models.CharField(max_length=512)
    mechanicaltilt = models.CharField(max_length=512)
    antennatypes = models.CharField(max_length=512)
    beautifytypes = models.CharField(max_length=512)
    antennafactory = models.CharField(max_length=512)
    antennamodel = models.CharField(max_length=512)
    antennanum = models.CharField(max_length=512)
    horizontalpowerangle = models.CharField(max_length=512)
    verticalpowerangle = models.CharField(max_length=512)
    antennagain = models.CharField(max_length=512)
    picture1 = models.CharField(max_length=512)
    picture2 = models.CharField(max_length=512)
    picture3 = models.CharField(max_length=512)
    picture4 = models.CharField(max_length=512)
    towermast = models.CharField(max_length=512)
    txrxmod = models.CharField(max_length=512)
    verticalrange = models.CharField(max_length=512)
    install = models.CharField(max_length=512)

    def init1(self, *args):
        if args:
            if type(args[0]) is list:  # object is being created, thus no primary key field yet
                args = args[0]
                self.antennaid = args[0]
                self.antennaid1 = args[1]
                self.province = args[2]
                self.city = args[3]
                self.district = args[4]
                self.lon = args[5]
                self.lat = args[6]
                self.physicalstationid = args[7]
                self.rruid = args[8]
                self.cellid1 = args[9]
                self.directionangle = args[10]
                self.antennaheight = args[11]
                self.electricaldowntilt = args[12]
                self.mechanicaltilt = args[13]
                self.antennatypes = args[14]
                self.beautifytypes = args[15]
                self.antennafactory = args[16]
                self.antennamodel = args[17]
                self.antennanum = args[18]
                self.horizontalpowerangle = args[19]
                self.verticalpowerangle = args[20]
                self.antennagain = args[21]
                self.picture1 = args[22]
                self.picture2 = args[23]
                self.picture3 = args[24]
                self.picture4 = args[25]
                self.towermast = args[26]
                self.txrxmod = args[27]
                self.verticalrange = args[28]
                self.install = args[29]
        return self

    def makeDataToOss(self):
        # para_dict = {
        #     'timestamp': '1512009575000',
        #     'objectTypeId': 'L00863',
        #     'objectId': 'null',
        #     'complaintId': 'null',
        #     'cell_4g': '',
        #     'cell_3g': '',
        #     'cell_2g': '',
        #     'test': '',
        #     'ANT_ID': self.antennaid,
        #     'NMS_ORIG_RES_NAME': self.antennaid1,
        #     'PROVINCE_ID': '110',
        #     'CITY_ID': CITYID[self.city],
        #     'DISTRICT_ID': DISTRICT_ID[self.district],
        #     'LONGITUDE': self.lon,
        #     'LATITUDE': self.lat,
        #     'PHY_ID': self.physicalstationid,
        #     'RELATED_RRU': self.rruid,
        #     'RELATED_CELL': self.cellid1,
        #     'ANT_AZIMUTH': self.directionangle,
        #     'ANT_HIGH': self.antennaheight,
        #     'ANT_ELECTANGLE': self.electricaldowntilt,
        #     'ANT_MACHANGLE': self.mechanicaltilt,
        #     'ANT_TYPE': '2',
        #     'BEA_TYPE': '2',
        #     'ANT_EQUIP': self.antennafactory,
        #     'ANT_EQUIPMODULE': self.antennamodel,
        #     'PORT_NUM': self.antennanum,
        #     'LEVEL_POWER': self.horizontalpowerangle,
        #     'APEAK_POWER': self.verticalpowerangle,
        #     'ANT_GAIN': self.antennagain,
        #     'ATTACH_ENT': self.picture1,
        #     'ATTACH_COV': self.picture2,
        #     'ATTACH_PHY': self.picture3,
        #     'ATTACH_QUE': self.picture4,
        #     'TOWER_TYPE': '3',
        #     'TX_RX_MODE': TX_RX_MODElist[self.txrxmod],
        #     'VERTICAL_DIST': self.verticalrange,
        #     'PHY_TYPE': '',
        #
        # }
        # try:
        #     AbstractAsk.get_new_cookie()
        #     modify_url = 'http://10.245.0.91:10101/wonop/wonop/config/maintain/detail/config_maintain_property_add_nocheckEx.action'
        #     respond_msg = oss_ask(modify_url, para_dict, None, AskModify)
        #     if respond_msg == 'true':
        #         self.save()

templates/management/add_book.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}添加图书{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图书</h1>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">书名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_author" class="col-md-3 control-label">作者：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="author" id="id_author">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_category" class="col-md-3 control-label">类型：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="category" id="id_category">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_price" class="col-md-3 control-label">价格：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="price" id="id_price">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_pubdate" class="col-md-3 control-label">出版日期：</label>
                        <div class="col-md-9">
                            <input type="date" class="form-control" required name="publish_date" id="id_pubdate">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/management/add_img.html
{% extends "management/base.html" %}
{% block title %}添加图书{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% elif state == 'error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">添加失败</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图片</h1>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">名称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_description" class="col-md-3 control-label">描述：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="description" id="id_description">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_book" class="col-md-3 control-label">所属书籍：</label>
                        <div class="col-md-9">
                            <select name="book" id="id_book" class="form-control">
                                {% for book in book_list %}
                                    <option value="{{ book.id }}">{{ book.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_img" class="col-md-3 control-label">图片：</label>
                        <div class="col-md-9">
                            <input type="file" id="id_img" name="img" class="form-control" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/management/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.zh-CN.js'%}"></script>


    <!--[if lt IE 9]>
			<script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
<!--Here is the navbar-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse-basepage">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {#            <a href="{% url 'homepage' %}" class="navbar-brand">Library</a>#}
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-basepage">
            <ul class="nav navbar-nav">
                <li id="homepage"><a href="{% url 'homepage' %}">主页</a></li>
                {% if user.myuser.permission > 0 %}
                    {#                    <li id="add_book"><a href="{% url 'add_book' %}">添加图书</a></li>#}
                    {#                    <li id="add_img"><a href="{% url 'add_img' %}">添加图片</a></li>#}
                    <li id="view_cell"><a href="{% url 'view_cell' %}">查看小区</a></li>
                    <li id="view_cell"><a href="{% url 'upexcel' %}">小区智能关联导入</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user %}
                    <li><p class="navbar-text">欢迎你&nbsp;&nbsp;<span id="base_name">{{ user.myuser.nickname }}</span></p>
                    </li>
                    <li><a href="{% url 'logout' %}">注销</a></li>
                    <li><a href="{% url 'set_password' %}">修改密码</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">注册</a></li>
                    <li><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
<!-- /nav -->
<!-- header -->
<header class="jumbotron subhead" id="header-base">
    <div class="container">
        <h1>智能运维</h1>
        <h3>&emsp;&emsp;勤于思考，多动手</h3>
    </div>
</header>
<!-- /.header -->
<!-- main part -->
{% block content %}{% endblock %}
<!-- /.main -->

<!-- footer -->
<footer class="footer" role="contentinfo">
    <hr>
    <div class="container">
        <p class="text-center"><strong>ChinaUnicom</strong></p>
        <p class="text-center">©All rights reserved</p>
        <h5 class="text-center"> Powered by&nbsp;<a href="http://luowl12@chinaunicom.com/">罗维良</a></h5>
    </div>
</footer>
<!-- /.footer-->
<script type="text/javascript">
    $('#{{ active_menu }}').addClass("active");

</script>
</body>
</html>

templates/management/detail.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}查看图书{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-5">
                    {% if book.img_set.all %}
                        <div id="carousel-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for img in book.img_set.all %}
                                    <li data-target="#carousel-generic" data-slide-to="{{ forloop.counter0 }}"
                                        {% if forloop.first %}class="active"{% endif %}></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                {% for img in book.img_set.all %}
                                    <div {% if forloop.first %}class="item active"{% else %}class="item"{% endif %}>
                                        <img class="img-rounded" src="{% url 'media' img.img %}">
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    {% else %}
                        <p class="text-center">暂无图片</p>
                    {% endif %}
                </div>
                <div class="col-md-6 col-md-offset-1">
                    <h2 class="text-center">{{ book.name }}</h2>
                    <br>
                    <h3>作者：{{ book.author }}</h3>
                    <h3>类别：{{ book.category }}</h3>
                    <h3>出版日期：{{ book.publish_date|date:"Y-m-d" }}</h3>
                    <h3>价格：{{ book.price|floatformat:2 }}</h3>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/management/importresult.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}智能关联导入{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 well">
                <h2>{{ flagstr }}</h2>
                <h3 class="text-center"><span class="text-info"></span></h3>
            </div>
        </div>
    </div>

{% endblock %}

templates/management/index.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}智能关联导入{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 well">
                <h2></h2>
                <h3 class="text-center"><span class="text-info"></span></h3>
            </div>
        </div>
    </div>



{% endblock %}

templates/management/login.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}登陆{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'not_exist_or_password_error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">用户不存在或密码错误</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请登陆</h1>

                    <div class="form-group">
                        <label for="id_user_name" class="col-md-3 control-label">用户名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_user_name" required name="username"
                                   autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_password" class="col-md-3 control-label">密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="password" id="id_password">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">登陆</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/management/signup.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}注册{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">注册成功！</h2>
                    </div>
                {% elif state == 'repeat_error' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码重复错误</h2>
                    </div>
                {% elif state == 'empty' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码不能为空</h2>
                    </div>
                {% elif state == 'user_exist' %}
                    <div class="well">
                        <h2 class="text-danger text-center">用户已经存在</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请注册</h1>

                    <div class="form-group">
                        <label for="id_user_name" class="col-md-3 control-label">用户名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_user_name" required name="username"
                                   autofocus>
                            <span class="help-block">用于登陆，可以包括大小写字母和下划线。</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">昵称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="nickname" id="id_name">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_passwd" class="col-md-3 control-label">密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="password" id="id_passwd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_repasswd" class="col-md-3 control-label">重复密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="repeat_password"
                                   id="id_repasswd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_email" class="col-md-3 control-label">电子邮件：</label>
                        <div class="col-md-9">
                            <input type="email" class="form-control" required name="email" id="id_email">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_region" class="col-md-3 control-label">地市：</label>
                        <div class="col-md-9">
                             <select type="region" class="form-control" required name="region" id="id_region">
                                <option>本部</option>
                                <option>南宁市</option>
                                <option>柳州市</option>
                                <option>桂林市</option>
                                <option>梧州市</option>
                                <option>北海市</option>
                                <option>防城港市</option>
                                <option>钦州市</option>
                                <option>贵港市</option>
                                <option>玉林市</option>
                                <option>百色市</option>
                                <option>贺州市</option>
                                <option>河池市</option>
                                <option>来宾市</option>
                                <option>崇左市</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_department" class="col-md-3 control-label">部门：</label>
                        <div class="col-md-9">
                            <select type="department" class="form-control" required name="department" id="id_department">
                                <option>区公司网优</option>
                                <option>区公司网建</option>
                                <option>区公司运维</option>
                                <option>分公司网优</option>
                                <option>分公司网建</option>
                                <option>分公司运维</option>
                            </select>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit" id="id_submit">注册</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock %}